### ISSUE TITLE
EnzymeExt ignores runtime activity

### ISSUE THREAD

**Issue by ptiede** [SciML/OptimizationBase.jl#115]
In Enzyme 0.13 runtime activity is now enabled in the `ReverseMode` type explicitly. For instance with ADtypes it would be done with 

```julia
OptimizationFunction(f, AutoEnzyme(;mode=set_runtime_activity(Reverse)))
```

However, this isn't being respected in `OptimizationEnzymeExt` where `Reverse` and `Forward` are hardcoded. 
For example

https://github.com/SciML/OptimizationBase.jl/blob/1ebca6fc7d34c5cf2f4a840caad061b92d021768/ext/OptimizationEnzymeExt.jl#L98-L113

forces `Enzyme.Reverse` regardless of the passed mode.

**Comment by Vaibhavdixit02** [comment]
@gdalle how should this be accessed with SecondOrder, is `so_adtype.inner.mode` and `so_adtype.outer.mode` the recommended way?

**Comment by gdalle** [comment]
DifferentiationInterface makes the functions `inner` and `outer` public, without exporting them, so if you have `backend = SecondOrder(AutoEnzyme(; mode=Forward), AutoEnzyme(; mode=Reverse))` then you can do `inner(backend).mode`.
Note that `inner` and `outer` will function as the identity on any `AbstractADType` that is not a `SecondOrder`.

**Comment by Vaibhavdixit02** [comment]
That makes sense, I just needed to confirm

**Comment by gdalle** [comment]
Always a better idea to use documented accessors instead of private internals ;) wink wink SparseMatrixColorings
