### ISSUE TITLE
Why is there still a Zygote extension?

### ISSUE THREAD

**Issue by gdalle** [SciML/OptimizationBase.jl#120]
I understand your wish to keep specializing on Enzyme for the time being, but why isn't Zygote handled like the other backends you removed?

**Comment by Vaibhavdixit02** [comment]
To use Buffer for the inplace constraint functions

**Comment by Vaibhavdixit02** [comment]
It still uses DI btw in the extension

**Comment by gdalle** [comment]
Oh right, that makes sense
