### ISSUE TITLE
Release patch with runtime activity support?

### ISSUE THREAD

**Issue by wsmoses** [SciML/OptimizationBase.jl#128]
It landed 2 weeks ago but look like it hasn't had a release.

Seems to be blocking some downstream things

**Comment by gdalle** [comment]
Note that for runtime activity to be supported here it might have to be supported in DI, which requires a merge on https://github.com/EnzymeAD/Enzyme.jl/pull/1979.
I think that PR is good to go anyway?

**Comment by wsmoses** [comment]
It does not and it is already implemented here.

OptimizationBase does not use DI for Enzyme

**Comment by gdalle** [comment]
Except for sparse AD?

**Comment by wsmoses** [comment]
I am specifically asking to make a patch release of this landed PR https://github.com/SciML/OptimizationBase.jl/pull/124 , since people are hitting issues otherwise.

Nothing here depends on DI

**Comment by gdalle** [comment]
Sorry for the disturbance
