### ISSUE TITLE
Evaluate functional and gradient simultaneously

### ISSUE THREAD

**Issue by goerz** [SciML/OptimizationBase.jl#22]
Would it be possible to combine the evaluation of the gradient and the functional in a single function? It seems that currently, the [`OptimizationFunction`](https://galacticoptim.sciml.ai/stable/API/optimization_function/) is designed to evaluate `f` and `grad` separately. What I'm looking for is basically [`Optim.only_fg!`](https://julianlsolvers.github.io/Optim.jl/stable/#user/tipsandtricks/#avoid-repeating-computations`), for all backends.

**Comment by Vaibhavdixit02** [comment]
https://github.com/SciML/OptimizationBase.jl/issues/8#issuecomment-2271288833
