### ISSUE TITLE
UndefVarError in OptimizationForwardDiffExt.jl

### ISSUE THREAD

**Issue by fjebaker** [SciML/OptimizationBase.jl#48]
Every so often I hit 
```
ERROR: UndefVarError: `x` not defined.
```
Unfortunately my code is too large to boil down to a MWE, but the cause is clear:

https://github.com/SciML/OptimizationBase.jl/blob/ba54a1f45360c4eb0346c9831c59a278b6d58044/ext/OptimizationForwardDiffExt.jl#L261

**Expected behavior**

`x` should be defined

**Comment by Vaibhavdixit02** [comment]
Which solver are you using out-of-place with though?
