### ISSUE TITLE
Add stochastic oracles

### ISSUE THREAD

**Issue by Vaibhavdixit02** [SciML/OptimizationBase.jl#61]
Right now Optimization.jl handles batching by a crude method. This amounts to asking users to pass in `data` arg to `solve`. This is expected to be an iterator, and more specifically a DataLoader https://fluxml.ai/Flux.jl/dev/reference/data/mlutils/#DataLoader. But, stochastic oracles are quite a fundamental part of modern optimization algorithms including recent work on second order and quasi-newton stochastic algs hence it would be more natural to have stochastic oracles which can be used directly by downstream algorithm implementations

**Comment by ChrisRackauckas** [comment]
Definitely agreed here, we can't really do a stochastic BFGS in the current form and that would be quite a useful method.

**Comment by Vaibhavdixit02** [comment]
Yup there's a stochastic newton etc as well 😅
