### ISSUE TITLE
Hessian of lagrangian very inefficient O(n^4)

### ISSUE THREAD

**Issue by baggepinnen** [SciML/OptimizationBase.jl#91]
This package does generally not generate Hessian of Lagrangian functions, and instead generates separate Hessian functions for the objective and _each individual_ constraint. The method for computing a Hessian for each individual constraint is extremely inefficient, repeatedly computing the entire constraint vector to grab a single element only. 
```julia
fcons = [(x) -> (_res = zeros(eltype(x), num_cons);
                 cons(_res, x);
                 _res[i]) for i in 1:num_cons]
        cons_hess_caches = [gen_conshess_cache(fcons[i], x, i) for i in 1:num_cons]
        cons_h = function (res, θ)
            fetch.([Threads.@spawn numauto_color_hessian!(
                        res[i], fcons[i], θ, cons_hess_caches[i]) for i in 1:num_cons])
        end
```
The Lagrangian function is a scalar function, so computing it can be done with complexity growing quadratically in the number of optimization variables. The code above has a worst-case complexity of `n_cons^2 * n_vars^2` which, if you have about as many constraints as variables, is `n_vars^4`. I notice that someone has put a `Threads.@spawn` in there, which does more to blow up memory requirements than to actually make this fast.

**Comment by Vaibhavdixit02** [comment]
It took me a while but I have gotten around to improving things for this https://github.com/SciML/OptimizationBase.jl/pull/90/files#diff-7dfd1f414a8b2066bb9d673fb65b7fc09f9e695c5611bc7ff0ef534507ba0880R295, I hope to have this out in a couple of weeks!
